pipeline {
    agent any;
 environment{
      targetAppStarterDeployRemoteDirectory='/docker/nginx/volumes/www'
    //   targetAppStarterRemovePrefix='manager'
    //   targetAppStarterSourceFiles='manager/**'
 }
stages {
        stage('代码编译') {
                      steps {
                            //http://registry.npm.taobao.org升级中2021-09-15 http://r.npm.taobao.org正常
                            // sh ' npm install mirror-config-china --registry=http://r.npm.taobao.org'
                            // sh ' npm install sass-loader node-sass -D --registry=http://r.npm.taobao.org'
                            // sh ' npm install --registry=http://r.npm.taobao.org'


                                //http://registry.npm.taobao.org升级中2021-09-15 http://r.npm.taobao.org正常
                            // sh  'npm config set registry https://registry.npmjs.org/'
                            // sh ' npm install mirror-config-china --registry=https://registry.npmjs.org/'
                            // sh ' npm install sass-loader node-sass -D --registry=https://registry.npmjs.org/'
                            // sh ' npm install --registry=https://registry.npmjs.org/'
                            sh  'npm install -g cross-env  --no-bin-links'
                            sh  'npm install' 
                            sh ' npm run build-dev'
                       }
        }
         stage("publish-target-dist in 147"){
            steps{
                    sshPublisher(
                        publishers: [
                            sshPublisherDesc(
                                configName: 'my-aliyun-server', transfers: [
                                    sshTransfer(
                                                 cleanRemote: false, excludes: '', execCommand: '', execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: '/opt/docker/nginx/volumes/www', remoteDirectorySDF: false, removePrefix: '**', sourceFiles: '/dist'
                                                )
                                                                          ], 
                                                 usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false
                                            )
                                    ]
                                )
            }
        }
 }
}
